language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jazzrose/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jazzrose/react-test npm run test

after_success:
  - docker build -t jazzrose/multi-client ./client
  - docker build -t jazzrose/multi-nginx ./nginx
  - docker build -t jazzrose/multi-server ./server
  - docker build -t jazzrose/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push jazzrose/multi-client
  - docker push jazzrose/multi-nginx
  - docker push jazzrose/multi-server
  - docker push jazzrose/multi-worker



deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'Multi-docker-env-1'
  bucket_name: 'elasticbeanstalk-eu-north-1-445718290187'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
